replicaCount: 1

image:
  repository: docker.io/hvaandres1409/my-node-app
  pullPolicy: IfNotPresent
  tag: "latest"

# Container & Service port
ports:
  - name: http
    containerPort: 3000
    protocol: TCP

service:
  type: LoadBalancer
  ports: 
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: internal-app