name: OSV-Scanner with Syft

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # v1.7.1
    with:
      scan-args: |-
        -r
        --skip-git
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # v1.7.1
    with:
      scan-args: |-
        -r
        --skip-git
        ./

  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Generate SBOM using Syft Docker image
        run: |
          docker run --rm -v $(pwd):/workspace ghcr.io/anchore/syft:latest sbom /workspace --output cyclonedx-json /workspace > sbom.json

  parse-sbom:
    runs-on: ubuntu-latest
    needs: generate-sbom
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Parse SBOM for critical vulnerabilities
        id: parse_sbom
        run: |
          critical_vulns=$(jq '[.components[] | select(.vulnerabilities | length > 0) | select(.vulnerabilities[] | .severity == "critical")] | length' sbom.json)
          echo "Critical vulnerabilities count: $critical_vulns"
          echo "::set-output name=critical::$critical_vulns"

      - name: Fail PR if critical vulnerabilities are found
        if: steps.parse_sbom.outputs.critical != '0'
        run: |
          echo "Critical vulnerabilities found in SBOM!"
          exit 1
