name: SBOM Security Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Syft
        run: |
          curl -sSL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          echo "$PATH"
          syft version

      - name: Generate SBOM
        run: |
          syft sbom . -o cyclonedx-json > sbom.json

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Parse SBOM for vulnerabilities
        id: parse_sbom
        run: |
          critical_vulns=$(jq '[.components[] | select(.vulnerabilities | length > 0) | select(.vulnerabilities[] | .severity == "critical")] | length' sbom.json)
          echo "Critical vulnerabilities count: $critical_vulns"
          echo "::set-output name=critical::$critical_vulns"

      - name: Fail PR if critical vulnerabilities are found
        if: steps.parse_sbom.outputs.critical != '0'
        run: |
          echo "Critical vulnerabilities found in SBOM!"
          exit 1
