name: OSV-Scanner with Syft

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  security-events: write
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory for SBOM
        run: mkdir -p /workspace

      - name: Generate SBOM using Syft Docker image
        run: |
          docker run --rm -v $(pwd):/workspace ghcr.io/anchore/syft:latest sbom /workspace --output cyclonedx-json /workspace/sbom.json

  index-sbom:
    runs-on: ubuntu-latest
    needs: generate-sbom
    steps:
      - name: Generate SBOM Index using Scout SBOM Indexer
        run: |
          docker run --rm -v $(pwd):/workspace docker/scout-sbom-indexer:latest index /workspace/sbom.json --output /workspace/indexed-sbom.json

  parse-sbom:
    runs-on: ubuntu-latest
    needs: index-sbom
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Parse Indexed SBOM for Critical Vulnerabilities
        id: parse_sbom
        run: |
          critical_vulns=$(jq '[.components[] | select(.vulnerabilities | length > 0) | select(.vulnerabilities[] | .severity == "critical")] | length' /workspace/indexed-sbom.json)
          echo "Critical vulnerabilities count: $critical_vulns"
          echo "::set-output name=critical::$critical_vulns"

      - name: Fail PR if Critical Vulnerabilities are Found
        if: steps.parse_sbom.outputs.critical != '0'
        run: |
          echo "Critical vulnerabilities found in Indexed SBOM!"
          exit 1
