name: Security-Dev-Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci install

      - name: Run npm audit
        id: audit
        run: |
          audit_results=$(npm audit --production --json)
          echo "$audit_results" > audit-results.json
          critical_vulns=$(echo "$audit_results" | jq '.metadata.vulnerabilities.critical')
          echo "::set-output name=critical::$critical_vulns"

      - name: Check for critical vulnerabilities
        if: steps.audit.outputs.critical != '0'
        run: |
          echo "Critical vulnerabilities found!"
          cat audit-results.json
          exit 1
